### ISSUE TITLE
category titles in Arabic

### ISSUE THREAD

**Issue by rmglade** [mnyrop/sudanphoto#22]
Hi Marii, we discussed putting the script for wax such that the Arabic lines have category title headings in Arabic--would that still be possible? That's the biggest change I need (and the only one I can't really do myself). Other than that, I can make the necessary tweaks to get out the rest of this version in the next week or so when I'm back in Khartoum. 

All the best,
Rebecca

**Comment by mnyrop** [comment]
Hi @rmglade, can you make/attach the list headings in english and arabic?
If so I can write some liquid for you to use.

e.g,

collection, *'collection' in arabic*
date, *'date' in arabic*
... and so on

**Comment by rmglade** [comment]
Hi @mnyrop , 
Thanks! The categories we have up now are:
Date, تاريخ
Location, مكان
Description, وصف
Archival ID, رقم الصورة
Collection, مجموعة الصور

**Comment by mnyrop** [comment]
this is done. you can preview the results at http://marii.info/sudanphoto/ and, if it looks right, merge in my [pull request](https://github.com/rmglade/sudanphoto/pull/8).
